### ISSUE TITLE
designs for the landing page

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/akeru#29]
We need a basic design for the landing page. We could try our hand at doing it ourselves or we could use some tweaked landing page from the figma community pages

AC:
- [ ] basic branding is respected with logo colours
- [ ] simple landing page design is done
- [ ] show and discuss design with team

**Comment by cxalem** [comment]
Hey team, I have the first version of the design: https://www.figma.com/file/B8cYeNpdAvfezzrzm0AqEk/Sprout?type=design&node-id=0%3A1&mode=design&t=muUPBq3Y1X1SHR4h-1

I didn't add the logo because I couldn't find it, if you can send it to me, it would be great! @GuiBibeau  😅

Any suggestion or feedback will be appreciated! Also if you want to add something, just let me know!
![sprout-landing](https://github.com/GuiBibeau/sprout/assets/96505286/cc8ed1fa-0b8c-4416-9756-9a12dfdee6b7)

**Comment by tobySolutions** [comment]
> Hey team, I have the first version of the design: https://www.figma.com/file/B8cYeNpdAvfezzrzm0AqEk/Sprout?type=design&node-id=0%3A1&mode=design&t=muUPBq3Y1X1SHR4h-1
> 
> I didn't add the logo because I couldn't find it, if you can send it to me, it would be great! @GuiBibeau 😅
> 
> Any suggestion or feedback will be appreciated! Also if you want to add something, just let me know! ![sprout-landing](https://private-user-images.githubusercontent.com/96505286/313422945-cc8ed1fa-0b8c-4416-9756-9a12dfdee6b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzU4NzksIm5iZiI6MTcxMTAzNTU3OSwicGF0aCI6Ii85NjUwNTI4Ni8zMTM0MjI5NDUtY2M4ZWQxZmEtMGI4Yy00NDE2LTk3NTYtOWExMmRmZGVlNmI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE1MzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmY4ZjIyZDE5YmE4M2ViMzVkNDBjZDI2NWQzMjA2ZmUyZWRlYjE3NDlmNDk3MmRkZTFjMDk2ZTc3ZGZiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._vFPbNyIwbHNAILhWWpWrdml9-y_qMX2YsUBBNyZM4Y)

Amazing stuff @cxalem!! Looks awesome!

**Comment by GuiBibeau** [comment]
We can consider this close :D I will send over the bounty
